setwd("~/YourWorkingDirectory")

library('dplyr')
feats = c('LME','BEME','r12_2','OP','Investment','ST_Rev','LT_Rev','AC','IdioVol',"LTurnover")

y_min = 1963
y_max = 2016

remove_rf = function(port_ret, factor_path){
  file_nm = paste(factor_path,'rf_factor.csv',sep='') #risk free rate from Fama French website
  r_f = read.table(file_nm, header = F, sep=',')
  for(i in c(1:ncol(port_ret))){
    port_ret[,i] = port_ret[,i]-(as.numeric(as.matrix(r_f)))/100
  }
  return(port_ret)
}

factor_path = '../data/factor/'

for (f in 1:length(feats)){
  print(feats[f])
  deciles = matrix(nrow = 648, ncol = 5)
  for (year in y_min:y_max){
    print(year)
    #same yearly data files as generated by tree portfolios
    data <- read.csv(paste("../data/data_chunk_files_quantile/",feats[f],"/y",year,".csv",sep=""), stringsAsFactors=FALSE)
    
    for (month in 1:12){
      i=12*(year-y_min)+month
      ymmask = (data$mm == month)
      retm=as.numeric(data[ymmask, "ret"])
      feature_m=as.numeric(data[ymmask,feats[f]])
      size_m = as.numeric(data[ymmask,"size"])
      permno_m = as.character(data[ymmask,"permno"])
      
      groups = ntile(feature_m, 5)
      
      for (j in 1:5){
        w = size_m[groups==j]/sum(size_m[groups==j])
        deciles[i,j] = retm[groups==j]%*% w
      }
    }
  }
  colnames(deciles) = paste(rep(feats[f],5),1:5,sep=".")
  
  deciles_excess = remove_rf(deciles[13:648,], factor_path)
  
  write.csv(deciles,file=paste("../data/quintile_portfolios/",feats[f],".csv",sep=""),row.names = FALSE)
  write.csv(deciles_excess,file=paste("../data/quintile_portfolios/",feats[f],"_excess.csv",sep=""),row.names = FALSE)
}